# Generated by Django 2.2.6 on 2021-04-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Введите заголовок', max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
