# Generated by Django 2.2.6 on 2021-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210401_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
