# Generated by Django 2.2.6 on 2021-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210330_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='C:/Dev/hw05_final/media/users/default.jpg', null=True, upload_to='users/'),
        ),
    ]
